artifact_uri: file:///Users/anashamrouni/Documents/InnopolisUniversity/Bachelor/PMLDL/Assignments/PMLDL-assignmant1/mlflow/0/210429299c3f4414b1170528c7b9336f/artifacts
end_time: 1758787526240
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 210429299c3f4414b1170528c7b9336f
run_name: capricious-stag-625
source_name: ''
source_type: 4
source_version: ''
start_time: 1758787518754
status: 3
tags: []
user_id: anashamrouni
